//
//  AppNotification.swift
//

import Foundation

/// 启动页结束
let PF_NOTIFICATION_LOADING_FINISHED = NSNotification.Name("NOTIFICATION_LOADING_FINISHED")

/// 登录成功
let PF_NOTIFICATION_LOGOIN_FINISHED = NSNotification.Name("NOTIFICATION_LOGOIN_FINISHED")

/// blood oxygen 更新
let PF_NOTIFICATION_OSXYGEN_FINISHED = NSNotification.Name("NOTIFICATION_OSXYGEN_FINISHED")

/// blood pressure 更新
let PF_NOTIFICATION_PRESSURE_FINISHED = NSNotification.Name("NOTIFICATION_PRESSURE_FINISHED")

/// blood temperature更新
let PF_NOTIFICATION_TEMPERATURE_FINISHED = NSNotification.Name("NOTIFICATION_TEMPERATURE_FINISHED")

/// 心率测试成功
let PF_NOTIFICATION_HEARTSUCCESS_FINISHED = NSNotification.Name("NOTIFICATION_HEARTSUCCESS_FINISHED")

/// 购买成功
let PF_NOTIFICATION_PAY_SUB_SUCCESS = NSNotification.Name("PF_NOTIFICATION_PAY_SUB_SUCCESS")

/// 心率测试成功退出订阅页面
let PF_NOTIFICATION_TEST_SUB_POP = NSNotification.Name("PF_NOTIFICATION_TEST_SUB_POP")

/// 添加提醒成功
let PF_NOTIFICATION_ADDREMINDER_SUCCESS = NSNotification.Name("PF_NOTIFICATION_ADDREMINDER_SUCCESS")


